# Use Ubuntu as the base image
FROM ubuntu:22.04

# Install Node.js and npm
# Set environment variables
ENV NODE_VERSION=18.x
# set work directory
WORKDIR /app/
# Install Node.js, npm, and other necessary packages
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - && \
    apt-get install -y nodejs && \
    apt-get install -y build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ARG VITE_API_URL

# add to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN npm install

# Expose Vite dev server port
EXPOSE 3000

# Start the Vite dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]