services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    environment:
      LT_LOAD_ONLY: "en,fr,de,it,nl,pt"
    restart: unless-stopped
    networks:
      - telereha

  db-dev:
    image: mongo:8.0.3
    container_name: db
    restart: always
    environment:
      - ./.env.dev
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db  # Correctly map this volume to persist data
    networks:
      - telereha

  django-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: django
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - 8001:8000
    volumes:
      - ./backend/:/app
      - static:/app/static
      - media:/app/media
      - ./frontend/src/config/:/app/config
    depends_on:
      - db-dev
      - redis
    networks:
      - telereha

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: celery
    restart: always
    command: python -m celery -A api.celery:app worker --loglevel=info --statedb=/app/celery_worker.state
    volumes:
      - ./backend:/app
    env_file:
      - ./.env.dev
    depends_on:
      - django-dev
      - redis
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.dev
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_WORKER_PREFETCH_MULTIPLIER=1
      - CELERY_WORKER_STATE_DB=/app/celery_worker.state
    networks:
      - telereha

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: celery-beat
    restart: always
    working_dir: /app
    command: >
      python -m celery -A api.celery:app beat -l info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.dev
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_CELERY_BEAT_DISABLE_SOLAR_SCHEDULE=True
    volumes:
      - ./backend:/app
    depends_on:
      - django-dev
      - redis
    networks:
      - telereha

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - telereha

  react-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react
    restart: always
    ports:
      - 3001:3000
    env_file:
      - ./.env.dev
    tty: true
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    depends_on:
      - django-dev
    networks:
      - telereha

  nginx-dev:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/dev.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django-dev
      - react-dev
      - db-dev
      - libretranslate
    networks:
      - telereha

volumes:
  node_modules:
  mongo_data:
  media:
  static:

networks:
  telereha:
    name: "telereha"
