FROM ubuntu:22.04
WORKDIR /app

# Install necessary system packages
RUN apt-get update && \
    apt-get -y install build-essential wget curl bzip2 libpq-dev gcc && \
    apt-get clean

# Download and install Miniforge (similar to Anaconda, compatible with multiple architectures)
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /opt/miniconda-installer.sh && bash /opt/miniconda-installer.sh -b -p /opt/conda

ENV PATH /opt/conda/bin:$PATH


COPY ./environment.yml .
RUN conda env create -f environment.yml
RUN echo "source activate teleRehabApp" > ~/.bashrc

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN apt-get update && apt-get install -y ffmpeg

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1 \
    DJANGO_SETTINGS_MODULE=api.settings.prod

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--reload", "api.wsgi:application"]