FROM continuumio/miniconda3:24.7.1-0
WORKDIR /app

ENV PATH=/opt/conda/bin:$PATH


COPY ./environment.yml .

# Accept Anaconda channel Terms of Service (required since conda 24.x)
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

RUN conda env create -f environment.yml
RUN echo "source activate teleRehabApp" > ~/.bashrc

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENV PYTHONUNBUFFERED=1 \
    DJANGO_SETTINGS_MODULE=api.settings.prod

# collect static, run migrations
RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "api.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "600"]
