name: teleRehabApp
channels:
  - defaults
dependencies:
  - django
  - djangorestframework
  - pymongo
  - websocket-client
  - pytest  # for testing
  - conda-forge::pytest-django
  - conda-forge::pytest-cov
  - black
  - flake8