image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  NGINX_IMAGE: $CI_REGISTRY_IMAGE/nginx

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-frontend:
  stage: build
  script:
    - docker build -t $FRONTEND_IMAGE:latest ./frontend
    - docker push $FRONTEND_IMAGE:latest
    - docker rmi -f $FRONTEND_IMAGE:latest  # Cleanup after push

build-backend:
  stage: build
  script:
    - docker build -t $BACKEND_IMAGE:latest ./backend
    - docker push $BACKEND_IMAGE:latest
    - docker rmi -f $BACKEND_IMAGE:latest  # Cleanup after push

build-nginx:
  stage: build
  script:
    - docker build -t $NGINX_IMAGE:latest ./nginx
    - docker push $NGINX_IMAGE:latest
    - docker rmi -f $NGINX_IMAGE:latest  # Cleanup after push

test-backend:
  stage: test
  script:
    - docker pull $BACKEND_IMAGE:latest  # Ensure the image is available
    - docker run --rm $BACKEND_IMAGE conda env list
    - docker run --rm $BACKEND_IMAGE pytest /srv/app/tests/
    - docker rmi -f $BACKEND_IMAGE:latest  # Cleanup after testing
