# Build context must be the repo root so we can access both frontend/ and nginx/
FROM ubuntu:22.04 AS react-builder

ENV NODE_VERSION=18.x
WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - && \
    apt-get install -y nodejs build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH /app/node_modules/.bin:$PATH

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend/ ./

ARG VITE_API_URL=http://localhost:8080/api
ENV VITE_API_URL=${VITE_API_URL}

RUN echo "Building with VITE_API_URL=$VITE_API_URL"
RUN VITE_API_URL=${VITE_API_URL} npm run build


FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/local-prod.nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react-builder /app/dist /usr/share/nginx/html

HEALTHCHECK --interval=30s --timeout=3s \
  CMD nginx -t || exit 1
