server {
  # Docker will map 8080 to 80
  listen 80;

  server_name localhost;
  include log.conf;

  # Serve static files from shared volume
  location /api_static/ {
    alias /srv/app/static;
    client_max_body_size 100M;  # Increase upload size for static files if necessary
    include /etc/nginx/app/include.forwarded;
  }
}


server {
  listen 8080;
  server_name localhost;
  include log.conf;

  # Serve media files from shared volume
  location /api_media/ {
    alias /srv/app/media;
    client_max_body_size 100M;  # Increase upload size for media files
    include /etc/nginx/app/include.forwarded;
  }
}

# Serve Django Backend (API & Admin)
server {
    listen 8000;
    server_name 159.100.246.89;

    location ~ ^/(admin|api) {
        proxy_pass http://django:8000;
        client_max_body_size 100M;  # Increase the allowed upload size
        proxy_redirect default;
        include /etc/nginx/app/include.forwarded;

    }
}

# Serve React Frontend (Vite)
server {
    listen 3000;
    server_name 159.100.246.89;

    location / {
        proxy_pass http://react:3000;
        client_max_body_size 100M;  # Ensure large files can be uploaded through React too
        proxy_redirect default;
        include /etc/nginx/app/include.forwarded;

    }
}
server {
  # Docker will map 8080 to 80
  listen 80;

  server_name localhost;
  include log.conf;

  # Serve static files from shared volume
  location /api_static/ {
    alias /srv/app/static;
    client_max_body_size 100M;  # Increase upload size for static files if necessary
    include /etc/nginx/app/include.forwarded;
  }
}


server {
  listen 8080;
  server_name localhost;
  include log.conf;

  # Serve media files from shared volume
  location /api_media/ {
    alias /srv/app/media;
    client_max_body_size 100M;  # Increase upload size for media files
    include /etc/nginx/app/include.forwarded;
  }
}

server {
  listen 8000;
  server_name localhost;
  include log.conf;

  # Redirect Django admin or API or websockets
  location ~ ^/(admin|api) {
    proxy_pass http://django:8000;
    client_max_body_size 100M;  # Increase the allowed upload size
    proxy_redirect default;
    include /etc/nginx/app/include.forwarded;

    # Optional: Add CORS headers if needed
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
    add_header Access-Control-Allow-Headers "Origin, Authorization, Content-Type";
  }
}

server {
  listen 3000;
  # Redirect any other requests to the React server
  server_name localhost;
  include log.conf;

  location / {
    proxy_pass http://react:3000;
    client_max_body_size 100M;  # Ensure large files can be uploaded through React too
    proxy_redirect default;
    include /etc/nginx/app/include.forwarded;
  }
}
