# Generated by Django 5.1.2 on 2024-10-22 07:03

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="custom_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("therapist", "Therapist"),
                    ("patient", "Patient"),
                    ("researcher", "Researcher"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_done", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.exercise"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.exercise"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specializations",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("PT", "Physical Therapy"),
                            ("OT", "Occupational Therapy"),
                            ("ST", "Speech Therapy"),
                            ("MT", "Massage Therapy"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "clinics",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("clinic_1", "Wellness Clinic A"),
                            ("clinic_2", "Rehab Center B"),
                            ("clinic_3", "Health Clinic C"),
                        ],
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("pwdhash", models.BinaryField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specializations",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("PT", "Physical Therapy"),
                            ("OT", "Occupational Therapy"),
                            ("ST", "Speech Therapy"),
                            ("MT", "Massage Therapy"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "clinics",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("clinic_1", "Wellness Clinic A"),
                            ("clinic_2", "Rehab Center B"),
                            ("clinic_3", "Health Clinic C"),
                        ],
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("pwdhash", models.BinaryField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("diagnosis", models.CharField(max_length=30)),
                (
                    "function",
                    models.CharField(
                        choices=[("motor", "Motor"), ("cognitive", "Cognitive")],
                        max_length=30,
                    ),
                ),
                (
                    "level_of_education",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("university", "University"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "professional_status",
                    models.CharField(
                        choices=[
                            ("unemployed", "Unemployed"),
                            ("employed", "Employed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("married", "Married"), ("single", "Single")],
                        max_length=30,
                    ),
                ),
                (
                    "lifestyle",
                    models.CharField(
                        choices=[
                            ("smoker", "Smoker"),
                            ("alcohol_1_week", "Alcohol consumption 1 time a week"),
                        ],
                        max_length=30,
                    ),
                ),
                ("personal_goals", models.CharField(max_length=30)),
                ("restrictions", models.CharField(max_length=30)),
                ("social_support", models.CharField(max_length=30)),
                ("access_word", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="core.therapist",
                    ),
                ),
            ],
        ),
    ]
