# Generated by Django 5.2.4 on 2025-07-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_user_created_at_user_custom_id_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='smsverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='SMSVerification',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
